export const PLAYLIST_CREATE_REQUEST = 'PLAYLIST_CREATE_REQUEST';
export const PLAYLIST_CREATE_SUCCESS = 'PLAYLIST_CREATE_SUCCESS';
export const PLAYLIST_CREATE_FAIL = 'PLAYLIST_CREATE_FAIL';

export const PLAYLIST_LIST_REQUEST = 'PLAYLIST_LIST_REQUEST';
export const PLAYLIST_LIST_SUCCESS = 'PLAYLIST_LIST_SUCCESS';
export const PLAYLIST_LIST_FAIL = 'PLAYLIST_LIST_FAIL';

export const PLAYLIST_DELETE_REQUEST = 'PLAYLIST_DELETE_REQUEST';
export const PLAYLIST_DELETE_SUCCESS = 'PLAYLIST_DELETE_SUCCESS';
export const PLAYLIST_DELETE_FAIL = 'PLAYLIST_DELETE_FAIL';
