export const SONG_LIST_REQUEST = 'SONG_LIST_REQUEST'
export const SONG_LIST_SUCCESS = 'SONG_LIST_SUCCESS'
export const SONG_LIST_FAIL = 'SONG_LIST_FAIL'

export const SONG_DETAILS_REQUEST = 'SONG_DETAILS_REQUEST'
export const SONG_DETAILS_SUCCESS = 'SONG_DETAILS_SUCCESS'
export const SONG_DETAILS_FAIL = 'SONG_DETAILS_FAIL'

export const SONG_DELETE_REQUEST = 'SONG_DELETE_REQUEST'
export const SONG_DELETE_SUCCESS = 'SONG_DELETE_SUCCESS'
export const SONG_DELETE_FAIL = 'SONG_DELETE_FAIL'

export const SONG_CREATE_REQUEST = 'SONG_CREATE_REQUEST'
export const SONG_CREATE_SUCCESS = 'SONG_CREATE_SUCCESS'
export const SONG_CREATE_FAIL = 'SONG_CREATE_FAIL'
export const SONG_CREATE_RESET = 'SONG_CREATE_FAIL_RESET'

export const SONG_UPDATE_REQUEST = 'SONG_UPDATE_REQUEST'
export const SONG_UPDATE_SUCCESS = 'SONG_UPDATE_SUCCESS'
export const SONG_UPDATE_FAIL = 'SONG_UPDATE_FAIL'
export const SONG_UPDATE_RESET = 'SONG_UPDATE_RESET'


export const SONG_CREATE_REVIEW_REQUEST = 'SONG_CREATE_REVIEW_REQUEST'
export const SONG_CREATE_REVIEW_SUCCESS = 'SONG_CREATE_REVIEW_SUCCESS'
export const SONG_CREATE_REVIEW_FAIL = 'SONG_CREATE_REVIEW_FAIL'
export const SONG_CREATE_REVIEW_RESET = 'SONG_CREATE_REVIEW_RESET'

export const SONG_TOP_REQUEST = 'SONG_TOP_REQUEST'
export const SONG_TOP_SUCCESS = 'SONG_TOP_SUCCESS'
export const SONG_TOP_FAIL = 'SONG_TOP_FAIL'
